-- 사용자_정보
CREATE TABLE USER
(
	id VARCHAR(32) NOT NULL,
	password VARCHAR(255) NOT NULL,
	name varchar(255) NOT NULL,
	PRIMARY KEY (id)
);

-- 권한 정보
CREATE TABLE AUTHORITY
(
	AUTHORITY VARCHAR(50) NOT NULL,
	AUTHORITY_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (AUTHORITY)
);

--회원-권한 테이블
CREATE TABLE USER_AUTHORITY
(
	USER_ID VARCHAR(50) NOT NULL,
	AUTHORITY VARCHAR(255) NOT NULL,
	PRIMARY KEY (USER_ID,AUTHORITY)
);

--권한 그룹 테이블
CREATE TABLE GROUPS
(
	ID VARCHAR(50) NOT NULL,
	GROUP_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

--권한 그룹별 사용자 테이블
CREATE TABLE GROUPS_USER
(
	GROUP_ID VARCHAR(50) NOT NULL,
	USER_ID VARCHAR(255) NOT NULL,
	PRIMARY KEY (GROUP_ID, USER_ID)
);

--권한 그룹별 소유 권한 테이블
CREATE TABLE GROUPS_AUTHORITY
(
	GROUP_ID VARCHAR(50) NOT NULL,
	AUTHORITY VARCHAR(255) NOT NULL,
	PRIMARY KEY (GROUP_ID,AUTHORITY)
);

--리소스 테이블
CREATE TABLE SECURED_RESOURCE
(
	RESOURCE_ID VARCHAR(50) NOT NULL,
	RESOURCE_NAME VARCHAR(50) NOT NULL,
	RESOURCE_PATTERN VARCHAR(100) ,
	RESOURCE_TYPE VARCHAR(255) ,
	SORT_ORDER NUMBER ,
	PRIMARY KEY (RESOURCE_ID)
);

--리소스에 따른 접근권한 테이블
CREATE TABLE SECURED_RESOURCE_AUTHORITY
(
	RESOURCE_ID VARCHAR(50) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	USER_NAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (RESOURCE_ID,AUTHORITY,USER_NAME)
);

---------------------------------------INSERT
INSERT INTO USER( id, password, name) VALUES ('admin', '$2a$10$bXHjdBEIu3urSvxONi4s0.vTPAk3IbFjEk.WMUbcczcYaSibNbFhy','바보');

INSERT INTO USER( id, password, name) VALUES ('user', '$2a$10$bXHjdBEIu3urSvxONi4s0.vTPAk3IbFjEk.WMUbcczcYaSibNbFhy', '유저당');

INSERT INTO AUTHORITY(AUTHORITY, AUTHORITY_NAME) VALUES ('ROLE_ADMIN', '어드민');

INSERT INTO AUTHORITY(AUTHORITY, AUTHORITY_NAME) VALUES ('ROLE_USER', '유저');

INSERT INTO USER_AUTHORITY(USER_ID, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY(USER_ID, AUTHORITY) VALUES ('user', 'ROLE_USER');




